version: "3.9"

services:
  api:
    container_name: maxanger_api
    build:
      context: .
      dockerfile: Maxanger.Api/Dockerfile
    ports:
      - "5000:5001"    # 5000 — порт VPS, 8080 — порт внутри контейнера
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5001"
      ASPNETCORE_ENVIRONMENT: "Production"
    restart: always
    
  postgres:
    image: postgres:latest
    container_name: maxanger_postgres
    environment:
      POSTGRES_DB: "maxanger"
      POSTGRES_USER: "max"
      POSTGRES_PASSWORD: "anger"
    ports:
      - "5432:5432"
    volumes:
      - maxanger_data:/var/lib/postgresql/data
  
  nginx:
    container_name: maxanger_nginx
    image: "nginx:latest"
    restart: always
    ports:
      - 80:80
    volumes:
      - "./nginx/logs:/etc/logs/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d/"
  
volumes:
  maxanger_data: