// <auto-generated />
using System;
using Maxanger.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maxanger.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311075854_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Chats.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("soft_deleted");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Chats.ChatMember", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ChatId", "UserId")
                        .HasName("pk_chat_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_members_user_id");

                    b.ToTable("chat_members", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Chats.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<long>("FromId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_id");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("soft_deleted");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_chat_messages_chat_id");

                    b.HasIndex("FromId")
                        .HasDatabaseName("ix_chat_messages_from_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.MessageContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_message_id");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_message_contents_chat_message_id");

                    b.ToTable("message_contents", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Polls.PollOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PollId")
                        .HasColumnType("bigint")
                        .HasColumnName("poll_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_poll_options");

                    b.HasIndex("PollId")
                        .HasDatabaseName("ix_poll_options_poll_id");

                    b.ToTable("poll_options", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Polls.PollVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("PollId")
                        .HasColumnType("bigint")
                        .HasColumnName("poll_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_poll_votes");

                    b.HasIndex("PollId")
                        .HasDatabaseName("ix_poll_votes_poll_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_poll_votes_user_id");

                    b.ToTable("poll_votes", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.UserCredentials", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("UserId")
                        .HasName("pk_user_credentials");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Event", b =>
                {
                    b.HasBaseType("Maxanger.Infrastructure.Entities.Messages.MessageContent");

                    b.Property<long>("AffectedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("affected_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_status");

                    b.HasIndex("AffectedUserId")
                        .HasDatabaseName("ix_events_affected_user_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Message", b =>
                {
                    b.HasBaseType("Maxanger.Infrastructure.Entities.Messages.MessageContent");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Polls.Poll", b =>
                {
                    b.HasBaseType("Maxanger.Infrastructure.Entities.Messages.MessageContent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("polls", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Whisper", b =>
                {
                    b.HasBaseType("Maxanger.Infrastructure.Entities.Messages.MessageContent");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<long>("ToId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_id");

                    b.HasIndex("ToId")
                        .HasDatabaseName("ix_whispers_to_id");

                    b.ToTable("whispers", (string)null);
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Chats.ChatMember", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Chats.Chat", "Chat")
                        .WithMany("ChatMembers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_members_chat_chat_id");

                    b.HasOne("Maxanger.Infrastructure.Entities.User", "User")
                        .WithMany("ChatMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_members_user_user_id");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Chats.ChatMessage", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Chats.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_chat_id");

                    b.HasOne("Maxanger.Infrastructure.Entities.User", "From")
                        .WithMany("ChatMessages")
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_user_from_id");

                    b.Navigation("Chat");

                    b.Navigation("From");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.MessageContent", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Chats.ChatMessage", "ChatMessage")
                        .WithOne("Content")
                        .HasForeignKey("Maxanger.Infrastructure.Entities.Messages.MessageContent", "ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_contents_chat_messages_chat_message_id");

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Polls.PollOption", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Messages.Polls.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_options_message_content_poll_id");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Polls.PollVote", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Messages.Polls.Poll", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_votes_polls_poll_id");

                    b.HasOne("Maxanger.Infrastructure.Entities.User", "User")
                        .WithMany("PollVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_votes_user_user_id");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.UserCredentials", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.User", "User")
                        .WithOne("UserCredentials")
                        .HasForeignKey("Maxanger.Infrastructure.Entities.UserCredentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Event", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.User", "AffectedUser")
                        .WithMany("Events")
                        .HasForeignKey("AffectedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_user_affected_user_id");

                    b.HasOne("Maxanger.Infrastructure.Entities.Messages.MessageContent", null)
                        .WithOne()
                        .HasForeignKey("Maxanger.Infrastructure.Entities.Messages.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_message_contents_id");

                    b.Navigation("AffectedUser");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Message", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Messages.MessageContent", null)
                        .WithOne()
                        .HasForeignKey("Maxanger.Infrastructure.Entities.Messages.Message", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_message_contents_id");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Polls.Poll", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Messages.MessageContent", null)
                        .WithOne()
                        .HasForeignKey("Maxanger.Infrastructure.Entities.Messages.Polls.Poll", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_polls_message_contents_id");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Whisper", b =>
                {
                    b.HasOne("Maxanger.Infrastructure.Entities.Messages.MessageContent", null)
                        .WithOne()
                        .HasForeignKey("Maxanger.Infrastructure.Entities.Messages.Whisper", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_whispers_message_contents_id");

                    b.HasOne("Maxanger.Infrastructure.Entities.User", "To")
                        .WithMany("Whispers")
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_whispers_user_to_id");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Chats.Chat", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Chats.ChatMessage", b =>
                {
                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("ChatMessages");

                    b.Navigation("Events");

                    b.Navigation("PollVotes");

                    b.Navigation("UserCredentials")
                        .IsRequired();

                    b.Navigation("Whispers");
                });

            modelBuilder.Entity("Maxanger.Infrastructure.Entities.Messages.Polls.Poll", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
